version: '3.4'

services: 
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sa_123456789!
    ports:
      - "1450:1433"
    volumes:
      - C:/SQL2019/Docker/data:/var/opt/mssql/data
      - C:/SQL2019/Docker/log:/var/opt/mssql/log
      - C:/SQL2019/Docker/secrets:/var/opt/mssql/secrets
  vouchers.static-files:
    image: ${DOCKER_REGISTRY-}vouchers-static-files
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:/vouchers/images:/app/wwwroot/images
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:80"
      - "4001:443"
    build:
      context: .
      dockerfile: Vouchers.StaticFiles/Dockerfile
  vouchers.identity-server:
    image: ${DOCKER_REGISTRY-}vouchers-identity-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:80"
      - "5001:443"
    build:
      context: .
      dockerfile: Vouchers.IdentityServer/Dockerfile
    depends_on:
      - db
  vouchers.api:
    image: ${DOCKER_REGISTRY-}vouchers-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:5000
    volumes:
      - C:/vouchers/images:/app/images
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6080:80"
      - "6443:443"
    build:
      context: .
      dockerfile: Vouchers.API/Dockerfile
    depends_on:
      - db
      - vouchers.static-files
      - vouchers.identity-server