//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vouchers.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vouchers.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor account does not exist.
        /// </summary>
        internal static string CreditorAccountDoesNotExist {
            get {
                return ResourceManager.GetString("CreditorAccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor account is not activated.
        /// </summary>
        internal static string CreditorAccountIsNotActivated {
            get {
                return ResourceManager.GetString("CreditorAccountIsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor account does not exist.
        /// </summary>
        internal static string DebtorAccountDoesNotExist {
            get {
                return ResourceManager.GetString("DebtorAccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor account is not activated.
        /// </summary>
        internal static string DebtorAccountIsNotActivated {
            get {
                return ResourceManager.GetString("DebtorAccountIsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain account does not exist.
        /// </summary>
        internal static string DomainAccountDoesNotExist {
            get {
                return ResourceManager.GetString("DomainAccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain does not exist.
        /// </summary>
        internal static string DomainDoesNotExist {
            get {
                return ResourceManager.GetString("DomainDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity does not exist.
        /// </summary>
        internal static string IdentityDoesNotExist {
            get {
                return ResourceManager.GetString("IdentityDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity does not have account in domain.
        /// </summary>
        internal static string IdentityDoesNotHaveAccountInDomain {
            get {
                return ResourceManager.GetString("IdentityDoesNotHaveAccountInDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer account does not exist.
        /// </summary>
        internal static string IssuerAccountDoesNotExist {
            get {
                return ResourceManager.GetString("IssuerAccountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer account is not activated.
        /// </summary>
        internal static string IssuerAccountIsNotActivated {
            get {
                return ResourceManager.GetString("IssuerAccountIsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer {0} does not have account item for unit {1}.
        /// </summary>
        internal static string IssuerDoesNotHaveAccountItemForUnit {
            get {
                return ResourceManager.GetString("IssuerDoesNotHaveAccountItemForUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer operations are not allowed.
        /// </summary>
        internal static string IssuerOperationsAreNotAllowed {
            get {
                return ResourceManager.GetString("IssuerOperationsAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max count of contracts exceeded.
        /// </summary>
        internal static string MaxCountOfContractsExceeded {
            get {
                return ResourceManager.GetString("MaxCountOfContractsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not allowed.
        /// </summary>
        internal static string OperationIsNotAllowed {
            get {
                return ResourceManager.GetString("OperationIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction request is already performed.
        /// </summary>
        internal static string TransactionRequestIsAlreadyPerformed {
            get {
                return ResourceManager.GetString("TransactionRequestIsAlreadyPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction request is not found.
        /// </summary>
        internal static string TransactionRequestIsNotFound {
            get {
                return ResourceManager.GetString("TransactionRequestIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type does not exist.
        /// </summary>
        internal static string UnitTypeDoesNotExist {
            get {
                return ResourceManager.GetString("UnitTypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not have account for voucher {1}.
        /// </summary>
        internal static string UserDoesNotHaveAccountForVoucher {
            get {
                return ResourceManager.GetString("UserDoesNotHaveAccountForVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidFrom cannot be modified on active offers.
        /// </summary>
        internal static string ValidFromCannotBeModifiedOnActiveOffers {
            get {
                return ResourceManager.GetString("ValidFromCannotBeModifiedOnActiveOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidFrom cannot be set to past.
        /// </summary>
        internal static string ValidFromCannotBeSetToPast {
            get {
                return ResourceManager.GetString("ValidFromCannotBeSetToPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidTo cannot be less than current datetime.
        /// </summary>
        internal static string ValidToCannotBeLessThanCurrentDatetime {
            get {
                return ResourceManager.GetString("ValidToCannotBeLessThanCurrentDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidTo cannot be less than ValidFrom.
        /// </summary>
        internal static string ValidToCannotBeLessThanValidFrom {
            get {
                return ResourceManager.GetString("ValidToCannotBeLessThanValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher does not exist.
        /// </summary>
        internal static string VoucherDoesNotExist {
            get {
                return ResourceManager.GetString("VoucherDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher value does not exist.
        /// </summary>
        internal static string VoucherValueDoesNotExist {
            get {
                return ResourceManager.GetString("VoucherValueDoesNotExist", resourceCulture);
            }
        }
    }
}
