//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vouchers.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vouchers.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account holder and unit type issuer are different.
        /// </summary>
        internal static string AccountHolderAndUnitTypeIssuerAreDifferent {
            get {
                return ResourceManager.GetString("AccountHolderAndUnitTypeIssuerAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account item unit and transaction unit are different.
        /// </summary>
        internal static string AccountItemUnitAndTransactionUnitAreDifferent {
            get {
                return ResourceManager.GetString("AccountItemUnitAndTransactionUnitAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is greater than balance.
        /// </summary>
        internal static string AmountIsGreaterThanBalance {
            get {
                return ResourceManager.GetString("AmountIsGreaterThanBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is greater than supply.
        /// </summary>
        internal static string AmountIsGreaterThanSupply {
            get {
                return ResourceManager.GetString("AmountIsGreaterThanSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is not positive.
        /// </summary>
        internal static string AmountIsNotPositive {
            get {
                return ResourceManager.GetString("AmountIsNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot disable exchangeability.
        /// </summary>
        internal static string CannotDisableExchangeability {
            get {
                return ResourceManager.GetString("CannotDisableExchangeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate with different unit types.
        /// </summary>
        internal static string CannotOperateWithDifferentUnitTypes {
            get {
                return ResourceManager.GetString("CannotOperateWithDifferentUnitTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit account and item have different units.
        /// </summary>
        internal static string CreditAccountAndItemHaveDifferentUnits {
            get {
                return ResourceManager.GetString("CreditAccountAndItemHaveDifferentUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit and debit accounts are equal.
        /// </summary>
        internal static string CreditAndDebitAccountsAreEqual {
            get {
                return ResourceManager.GetString("CreditAndDebitAccountsAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor and debtor are the same.
        /// </summary>
        internal static string CreditorAndDebtorAreTheSame {
            get {
                return ResourceManager.GetString("CreditorAndDebtorAreTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current validFrom is greater than new validTo.
        /// </summary>
        internal static string CurrentValidFromIsGreaterThanNewValidTo {
            get {
                return ResourceManager.GetString("CurrentValidFromIsGreaterThanNewValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit account and item have different units.
        /// </summary>
        internal static string DebitAccountAndItemHaveDifferentUnits {
            get {
                return ResourceManager.GetString("DebitAccountAndItemHaveDifferentUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer cannot require exchangeability.
        /// </summary>
        internal static string IssuerCannotRequireExchangeability {
            get {
                return ResourceManager.GetString("IssuerCannotRequireExchangeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer cannot set maxDurationBeforeValidityStart.
        /// </summary>
        internal static string IssuerCannotSetMaxDurationBeforeValidityStart {
            get {
                return ResourceManager.GetString("IssuerCannotSetMaxDurationBeforeValidityStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer cannot set minDurationBeforeValidityEnd.
        /// </summary>
        internal static string IssuerCannotSetMinDurationBeforeValidityEnd {
            get {
                return ResourceManager.GetString("IssuerCannotSetMinDurationBeforeValidityEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item unit cannot be exchanged.
        /// </summary>
        internal static string ItemUnitCannotBeExchanged {
            get {
                return ResourceManager.GetString("ItemUnitCannotBeExchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New validFrom is greater than current validFrom.
        /// </summary>
        internal static string NewValidFromIsGreaterThanCurrentValidFrom {
            get {
                return ResourceManager.GetString("NewValidFromIsGreaterThanCurrentValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New validFrom is greater than current validTo.
        /// </summary>
        internal static string NewValidFromIsGreaterThanCurrentValidTo {
            get {
                return ResourceManager.GetString("NewValidFromIsGreaterThanCurrentValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New validTo is less than current validFrom.
        /// </summary>
        internal static string NewValidToIsLessThanCurrentValidFrom {
            get {
                return ResourceManager.GetString("NewValidToIsLessThanCurrentValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request amount is not satisfied by transaction.
        /// </summary>
        internal static string RequestAmountIsNotSatisfiedByTransaction {
            get {
                return ResourceManager.GetString("RequestAmountIsNotSatisfiedByTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request creditor is not satisfied by transaction.
        /// </summary>
        internal static string RequestCreditorIsNotSatisfiedByTransaction {
            get {
                return ResourceManager.GetString("RequestCreditorIsNotSatisfiedByTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request debtor is not satisfied by transaction.
        /// </summary>
        internal static string RequestDebtorIsNotSatisfiedByTransaction {
            get {
                return ResourceManager.GetString("RequestDebtorIsNotSatisfiedByTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request maxValidFrom is not satisfied by transaction.
        /// </summary>
        internal static string RequestMaxValidFromIsNotSatisfiedByTransaction {
            get {
                return ResourceManager.GetString("RequestMaxValidFromIsNotSatisfiedByTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request minValidTo is not satisfied by transaction.
        /// </summary>
        internal static string RequestMinValidToIsNotSatisfiedByTransaction {
            get {
                return ResourceManager.GetString("RequestMinValidToIsNotSatisfiedByTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request mustBeExchangeable is not satisfied by transaction.
        /// </summary>
        internal static string RequestMustBeExchangeableIsNotSatisfiedByTransaction {
            get {
                return ResourceManager.GetString("RequestMustBeExchangeableIsNotSatisfiedByTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request unit is not satisfied by transaction.
        /// </summary>
        internal static string RequestUnitIsNotSatisfiedByTransaction {
            get {
                return ResourceManager.GetString("RequestUnitIsNotSatisfiedByTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction and item have different unit types.
        /// </summary>
        internal static string TransactionAndItemHaveDifferentUnitTypes {
            get {
                return ResourceManager.GetString("TransactionAndItemHaveDifferentUnitTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction contains expired units.
        /// </summary>
        internal static string TransactionContainsExpiredUnits {
            get {
                return ResourceManager.GetString("TransactionContainsExpiredUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is already performed.
        /// </summary>
        internal static string TransactionIsAlreadyPerformed {
            get {
                return ResourceManager.GetString("TransactionIsAlreadyPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit is expired.
        /// </summary>
        internal static string UnitIsExpired {
            get {
                return ResourceManager.GetString("UnitIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidFrom is greater than validTo.
        /// </summary>
        internal static string ValidFromIsGreaterThanValidTo {
            get {
                return ResourceManager.GetString("ValidFromIsGreaterThanValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidTo is less than today.
        /// </summary>
        internal static string ValidToIsLessThanToday {
            get {
                return ResourceManager.GetString("ValidToIsLessThanToday", resourceCulture);
            }
        }
    }
}
